sudo: required
dist: xenial
language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install poetry
  - poetry install
# command to run tests
script:
  - poetry run pytest
  - coveralls
notifications:
  email:
    - luke@stcstores.co.uk
