sudo: required
dist: xenial
language: python
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo sudo apt-get update; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then sudo sudo apt-get update; fi
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"
  - "nightly"
# command to install dependencies
install:
  - make init
# command to run tests
script:
  - make test
