sudo: required
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - make init
# command to run tests
script:
  - make test
  - coveralls
notifications:
  email:
    - luke@stcstores.co.uk
