"""CCAPI."""

__title__ = "ccapi"
__description__ = "API integration for Cloud Commerce Pro."
__url__ = "http://github.com/axevalley/ccapi.git"
__version__ = "0.0.1"
__author__ = "Luke Shiner"
__author_email__ = "luke@lukeshiner.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Luke Shiner"
